{% set name = "assetid" %}
{% set version = "1.0.0" %}
{% set build = 0 %}
{% set hash = "dd81d75e589bd6702da0ec48d3b83414cddf109e7eee0c4eb03d7978c4106de0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: assetid-{{ version}}.tar.gz
  url: https://github.com/axiom-data-science/assetid/archive/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - assetid
    - assetid.tests

about:
  home: "https://github.com/axiom-data-science/{{ name }}"
  license: MIT
  summary: 'An ocean data asset ID parser developed and used by Axiom Data Science'

extra:
  recipe-maintainers:
    - kwilcox
