travis:
  secure:
    BINSTAR_TOKEN: V7Hby9j0Su8ylUgMNS62o7udxv7JHr+KBU4gR8FZbOsY8KlwlqtMTIHuK6FaLcPWYTaT5KXv+DM8DQzLJkek+7A880S+9Qu/qVrOdICxc2Qc1Hd/gFURIN1FlsL6o0vvqR0wbJPFJWCelFRuwENXRCLV71qJcwiwOU/8AB6QwGxNCkWZqdrvRByRiIfgOTf8qja2Z+qtFW1jcxFEn7GSNRq1vhpYUPvs6iTzyfzTXBdMGNbQZtzSQt01NUrVqP4hDsn7oJU9nsbCUV5Yqqnm894bwubkPSpJhS+x1FNA81LEtjxHHd3gY2ufvfbIRYc3oK3hTCmXiSdm9gCtJ7uJHuKqrEZzdJtrgQZ0TvjUarnWMPILEBqaG376I//3biYaEhjp0PFSCBQcpYLHvs4uQoFihYNn7vao5G9Bvak2+Kpi/BLte0DUKW/65SIvAByRKvbZBU0lbQ1AsG4mGOaXZr5XMxCfzZaO0Bl3oTkxtYiJuIGRm/QQ4CW/qpkzHx/CEXLe3tBQxSK1XSOhnugmaNrQqgc/96AEgTpsc6LFL19DdJS1XVZ9S5iSeU212TAM502Avdz9XWRyiebv2Hj/vZLjqjhOquPuIbakjbU+apCUUodxQFU2UfKPfeaCTuFiMqteQnikM2DidkuphI4nmw2qI4n1IAbDoNTxUsDqni8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
