travis:
  secure:
    BINSTAR_TOKEN: gFQM/ZL2NWz2I/zVz4CBO7cDxfGXONjoU2bdMjUUe2AcdgRwU6jv6rzjYzqqSqpp7qn/A3PI9imMUQkj/PE0fMdsYq4gvozCbueZ7M5MbaukUO9t1OYqd/MsWSGwmxfA3RIvzx2HuEtaA2OEusrHzbMBvNrclr1YYduxvF9R1+Jsvy9H1VATzWLJVZ0JYxBIsmh8FhTI1K6b6XwTwMeUGLVE3+5fs9AT4nb/raL0P56PUSZx94Z9pZb7hUkNWS3IdjarSss9SkPW3M/mRqeX7WTnxwlZS8GZ2BfKh09XYV/+ittRBv5ld2usebieioY2rNdejApJeusWkC536uqPkpOXQQLQucwRMWQABwqjqedJmCrx8eyqxtCihOw/tLNKmbB7AsfJXP4dPox51W3Xdz9LTtx6IdnHTIjhTsIxQBZFfdtVThuovbsEjjwyhtvZEp0rtGNr3lVN+gKES7czNFZbfkPWjjDAZNU9PKDGVkM86pHmTaGGNlEctNuC3eBDTASS5QnON8PbCC3HZFKHbCytyvPnNpXtS47ycEXgDlUF6lojW7Jh7yA1uwSkWQc2Cpf721CmQEqG4NPC4cGdhP/Kbk4NlrrZZBhp2GufybdiMK7S5txqWAV61Q0gahuel/JhE8/tHYGZC833VxoO4IofZbgR6d3sRFKOvUe3sPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
